export const API_URLS = {
  auth: {
    login: "/login",
  },
  admin: {
    menu: "/admin/menu",
    monitoring: "/admin/monitoring",
  },
  dashboard: {
    overview: "/admin/dashboard",
    currentMonthTripSales: "/admin/current-month-trip-sales-report",
    packageProfitMargin: "/admin/package-profit-margin",
  },
  reports: {
    averageBookingValueReport: "/admin/avg-booking-value-report",
    bookingSummary: "/admin/booking-summary",
    customerValue: "/admin/customerValue",
    dailyBalance: "/admin/monthlyDailyBalanceReport",
    dailyBalanceHistory: "/admin/monthly-daily-balance-reports",
    financialReport: "/admin/financial_report",
    guideEfficiency: "/admin/guideEfficency",
    guideDropdown: "/admin/guide/dropdown",
    highCancellationPackages: "/admin/high-cancellation-packages",
    hotels: "/admin/hotel",
    hotelUpdate: (hotelId) => `/admin/hotel/update/${hotelId}`,
    lowOccupancyReport: "/admin/low-occupancy-trip-report",
    lowPerformingPackages: "/admin/low-performing-packages",
    monthRunningBalance: "/admin/monthRunningBalance",
    overallSalesSummary: "/admin/overall-sales-summary",
    refundStatusReport: "/admin/refund-status-report",
    routes: "/admin/routes",
    routeWiseSalesSummary: "/admin/route-wise-sales-summary",
    routeDropdown: "/admin/routes/dropdown",
    tickets: "/admin/tickets",
    ticketUpdate: (ticketId) => `/admin/tickets/update/${ticketId}`,
    packages: "/admin/packages",
    packageCreate: "/admin/packages/create",
    singleRoute: (routeId) => `/admin/routes/${routeId}`,
    singleTrip: (tripId) => `/admin/single/trip/${tripId}`,
    singlePackage: (packageId) => `/packages/${packageId}`,
    transactions: "/admin/transaction",
    trips: "/admin/trip",
    tripUpdate: (tripId) => `/admin/trip/update/${tripId}`,
    tripPerformance: "/admin/tripPerformance",
    userGrowthReport: "/admin/user-growth-report",
    vehicles: "/admin/vehicles",
    vehicleDropdown: "/admin/vehicles/dropdown",
    vehicleWiseSeatReport: "/admin/vehiclewisetotalseat",
    vehicleTrackingReport: "/admin/useageOfVehicle",
    singleHotel: (hotelId) => `/hotel/${hotelId}`,
  },
};
