export const APP_ROUTES = {
  accountBalance: "/admin/account/balance",
  accountHistory: "/admin/account/history",
  averageBookingValueReport: "/admin/avg-booking-value-report",
  blogList: "/admin/blog-list",
  blogCreate: "/admin/blog/add",
  blogEdit: "/admin/blog/update/:blogId",
  bookings: "/admin/bookings",
  bookingInvoice: "/admin/bookinginvoice/:bookingId",
  bookingSummary: "/admin/bookings/summary",
  changePassword: "/admin/account/change-password",
  customerValue: "/admin/customerValueReport",
  dailyBalance: "/admin/account/daily-balance",
  dashboard: "/",
  financialReport: "/admin/financialReport",
  guide: "/admin/guide",
  guideCreate: "/admin/guide/add",
  guideEdit: "/admin/guide/update/:guideId",
  guideEfficiency: "/admin/guideEfficency",
  highCancellationPackages: "/admin/high-cancellation-packages",
  hotel: "/admin/hotel",
  hotelCreate: "/admin/hotel/create",
  hotelEdit: "/admin/hotel/:hotelId/edit",
  lowOccupancyReport: "/admin/low-occupancy-report",
  lowPerformingPackages: "/admin/low-performing-packages",
  monitoring: "/admin/monitoring",
  monthRunningBalance: "/admin/monthRunningBalance",
  overallSales: "/admin/account/overall-sales",
  packages: "/admin/packages",
  packageCreate: "/admin/packages/create",
  profile: "/admin/account/profile",
  refund: "/admin/refund",
  refundStatusReport: "/admin/refund-status-report",
  routes: "/admin/routes",
  tickets: "/admin/tickets",
  transactions: "/admin/transactions",
  trips: "/admin/trips",
  tripCreate: "/admin/trips/add",
  tripEdit: "/admin/trips/:tripId/edit",
  tripPerformance: "/admin/tripPerformance",
  userGrowthReport: "/admin/user-growth-report",
  vehicles: "/admin/vehicles",
  vehicleWiseSeatReport: "/admin/vehiclewiseseatreport",
  vehicleTrackingReport: "/admin/vehicletrackingreport",
  login: "/login",
};

export const getTripEditRoute = (tripId) => `/admin/trips/${tripId}/edit`;
export const getHotelEditRoute = (hotelId) => `/admin/hotel/${hotelId}/edit`;
export const getBookingInvoiceRoute = (bookingId) => `/admin/bookinginvoice/${bookingId}`;
export const getBlogEditRoute = (blogId) => `/admin/blog/update/${blogId}`;
